### ISSUE TITLE
Program logged: "Error: InvalidFee" on Devnet when creating AMM 

### ISSUE THREAD

**Issue by daoplays** [raydium-io/raydium-sdk-V1-demo#3]
From this commit:
https://github.com/raydium-io/raydium-sdk/commit/895abf5dfff8d83a1d42aa94ec278e18aad6f2a6

It seems that creating an AMM now needs a fee account, but there is just a comment there "mainnet only" on :
https://github.com/raydium-io/raydium-sdk-V1-demo/commit/a223c203076d861f6b47d2902791db09ad2ad90e

feeDestinationId: new PublicKey('7YttLkHDoNj9wyDur5pM1ejNaAvT9X4eqaYcHQqtj2G5'), // only mainnet use this

Is testing creating an AMM on devnet now broken or is there an equivalent account that is accepted there?

**Comment by rudy5348** [comment]
devnet please use 3XMrhbv989VxAMi3DErLV9eJht1pHppW5LbKxe9fkEFR
